%% Import data from spreadsheet


% to just import the data in aggregate

%    Workbook: C:\Users\John Bladon\Desktop\USV recordings .xlsx
%    Worksheet: Summary


opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = "Summary";
opts.DataRange = "A2:I105";

% Specify column names and types
opts.VariableNames = ["Cohort", "Animal", "Genotype", "Sex", "EarMarkings", "ToeMarkings", "LegMarkings", "Birthdate", "notes"];
opts.VariableTypes = ["double", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["ToeMarkings", "EarMarkings", "LegMarkings", "notes"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Cohort", "Animal", "Genotype", "Sex", "EarMarkings", "ToeMarkings", "LegMarkings", "Birthdate", "notes"],...
 "EmptyFieldRule", "auto");

% Import the data
USVSummary = readtable("C:\Users\John Bladon\Desktop\USV recordings.xlsx", opts, "UseExcel", false);

%% for individual sessions:
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\John Bladon\Desktop\USV recordings .xlsx
%    Worksheet: Cohort 1
%
% Auto-generated by MATLAB on 14-Oct-2021 21:41:37
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = "Summary";
opts.DataRange = "A2:I92";

% Specify column names and types
opts.VariableNames = ["Cohort", "Animal", "Genotype", "Sex", "EarMarkings", "ToeMarkings", "LegMarkings", "VarName8", "fileLocation"];
opts.VariableTypes = ["double", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify variable properties
opts = setvaropts(opts, ["Animal", "EarMarkings", "VarName8", "fileLocation"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Animal", "Genotype", "Sex", "EarMarkings", "ToeMarkings", "LegMarkings", "VarName8", "fileLocation"], "EmptyFieldRule", "auto");

% Import the data
USVSummary = readtable("C:\Users\John Bladon\Desktop\USV recordings .xlsx", opts, "UseExcel", false);


% Clear temporary variables
clear opts
%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
Sheetnames=["Cohort 1","Cohort 2","Cohort 3","Cohort 4","Cohorts 5 & 6"];

for i=1:length(Sheetnames)
    opts.Sheet = Sheetnames(i);
    opts.DataRange = "A2:H300";
    
    % Specify column names and types
    opts.VariableNames = ["Date", "FileName", "Animal", "Weight", "Time", "XFName", "OtherID", "VarName8"];
    opts.VariableTypes = ["datetime", "string", "string", "double", "string", "string", "string", "string"];
    
    % Specify variable properties
    opts = setvaropts(opts, ["FileName", "Animal", "Time", "XFName", "OtherID", "VarName8"], "WhitespaceRule", "preserve");
    opts = setvaropts(opts, ["FileName", "Animal", "Time", "XFName", "OtherID", "VarName8"], "EmptyFieldRule", "auto");
    opts = setvaropts(opts, "Date", "InputFormat", "");
    
    % Import the data
    CohortsTemp = readtable("C:\Users\John Bladon\Desktop\USV recordings .xlsx", opts, "UseExcel", false);
    CohortsTemp(CohortsTemp.FileName=="",:)=[];
    if i==1
        USVSession=CohortsTemp;
    else
        USVSession=vertcat(USVSession,CohortsTemp);
    end
end
% Clear temporary variables
clear opts
%%
% now fill in all data for all animals
% i think i want to just do a single table with ALL info


% It will be USV recordings.Session, it will have:
% 1. date
% 2. Filename
% 3. Animal (XF)
% 4. Weight
% 5. Age
% 6. Sex
% 7. Genotype
% 8. Cohort
% 9. Other markings


for i=1:height(USVSession)
    
    % first grab the data from the filename
    myfilename=USVSession.FileName{i};
    unders=find(myfilename=='_' | myfilename=='-');
    USVSession.Cohort(i)=str2double(myfilename(2:unders(1)-1)); % cohort
    USVSession.Age(i)=str2double(myfilename(unders(1)+2:unders(2)-1)); % age
    % pull rat name from file name
    myname=myfilename(unders(2)+1:end);
    
    % now match this to what we have, has to be animal name and correct
    % cohort
    mymatch=find(sum(myname==USVSummary{:,[2 5 6 7]},2) &...
        USVSummary.Cohort==USVSession.Cohort(i));
    if length(mymatch)~=1
        mymatch=input(['Rat' myname ' in cohort ' num2str(USVSession.Cohort(i)) ...
            ' has no match, which row is it?']);
    end
    % then we found the match
    USVSession.Genotype(i)=USVSummary.Genotype(mymatch);
    USVSession.Sex(i)=USVSummary.Sex(mymatch);
    myalias=USVSummary{mymatch,[2 5 6 7]};
    myalias(myalias=="")=[];
    USVSession.Alias{i}=myalias;
    USVSession.XFName(i)=USVSummary.Animal(mymatch);
    
end
        
    
